---

# Preflight checks

- name: Preflight - Lookup operating-system id
  set_fact:
    os_id: "{{ lookup('ini', 'ID type=properties file=/etc/os-release') | regex_replace('\"','') }}"

- name: Preflight - Lookup operating system version
  set_fact:
    os_version: "{{ lookup('ini', 'VERSION type=properties file=/etc/os-release') | regex_replace('\"','') }}"

- name: Preflight - Fail if host is not suitable for this benchmark
  fail:
    msg: "This benchmark is not suitable for the destination operating system"
  when: (os_id is not defined) or (os_version is not defined) or (os_version not in cis_target_os_versions) or (os_id != cis_target_os_id)
