---

# 1.1.4 Ensure nosuid option set on /tmp partition

- name: 1.1.4 - Ensure nosuid option set on /tmp partition
  debug:
    msg: "WARNING - This check has not been implemented yet."
  tags:
    - level-1
    - section-1
    - "1.1.4"
    - scored
    - todo

