---

# 1.1.3 Ensure nodev option set on /tmp partition

- name: 1.1.3 - Ensure nodev option set on /tmp partition
  debug:
    msg: "WARNING - This check has not been implemented yet."
  tags:
    - level-1
    - section-1
    - "1.1.3"
    - scored
    - todo

