---

# 1.1.9 Ensure nosuid option set on /var/tmp partition

- name: 1.1.9 - Ensure nosuid option set on /var/tmp partition
  debug:
    msg: "WARNING - This check has not been implemented yet."
  tags:
    - level-1
    - section-1
    - "1.1.9"
    - scored
    - todo

