---

# 1.5.2 Ensure XD/NX support is enabled

- name: 1.5.2 - Check if XD/NX support is enabled
  shell: "dmesg | grep NX"
  register: dmesg_1_5_2
  ignore_errors: true
  tags:
    - level-1
    - "1.5.2"
    - not-scored

- name: 1.5.2 - Ensure XD/NX support is enabled
  fail:
    msg: "Ensure XD/NX support is enabled."
  when: "'NX (Execute Disable) protection: active' not in dmesg_1_5_2.stdout"
  tags:
    - level-1
    - "1.5.2"
    - not-scored
