---

# 2.1.5 Ensure time services are not enabled

- name: 2.1.5 - Ensure time services are not enabled
  service:
    name: "{{ item }}"
    enabled: false
  with_items:
    - time-dgram
    - time-stream
  ignore_errors: true
  tags:
    - level-1
    - "2.1.5"
    - scored
