---

# 2.1.9 Ensure tftp server is not enabled

- name: 2.1.9 - Ensure tftp server is not enabled
  service:
    name: "tftp"
    enabled: false
  ignore_errors: true
  tags:
    - level-1
    - "2.1.9"
    - scored
