---

# 2.1.1 Ensure chargen services are not enabled

- name: 2.1.1 - Ensure chargen services are not enabled
  service:
    name: "{{ item }}"
    enabled: false
  with_items:
    - chargen-dgram
    - chargen-stream
  ignore_errors: true
  tags:
    - level-1
    - "2.1.1"
    - scored
