---

# 2.1.4 Ensure echo services are not enabled

- name: 2.1.4 - Ensure echo services are not enabled
  service:
    name: "{{ item }}"
    enabled: false
  with_items:
    - echo-dgram
    - echo-stream
  ignore_errors: true
  tags:
    - level-1
    - "2.1.4"
    - scored
