---

# 2.1.3 Ensure discard services are not enabled

- name: 2.1.3 - Ensure discard services are not enabled
  service:
    name: "{{ item }}"
    enabled: false
  with_items:
    - discard-dgram
    - discard-stream
  ignore_errors: true
  tags:
    - level-1
    - "2.1.3"
    - scored
