---

# 2.2.5 Ensure DHCP Server is not enabled

- name: 2.2.5 - Ensure DHCP Server is not enabled
  service:
    name: "dhcpd"
    enabled: false
  ignore_errors: true
  tags:
    - level-1
    - "2.2.5"
    - scored
