---

# 3.2.6 Ensure bogus ICMP responses are ignored

- name: 3.2.6 - Ensure bogus ICMP responses are ignored
  sysctl:
    name: "net.ipv4.icmp_ignore_bogus_error_responses"
    value: 1
    state: present
  tags:
    - level-1
    - "3.2.6"
    - scored

- name: 3.2.6 - Ensure bogus ICMP responses are ignored by active kernel parameters
  command: "{{ item }}"
  with_items:
    - "sysctl -w net.ipv4.icmp_ignore_bogus_error_responses=1"
    - "sysctl -w net.ipv4.route.flush=1"
  tags:
    - level-1
    - "3.2.6"
    - scored
