---

# 4.2.1.5 Ensure remote rsyslog messages are only accepted on designated log hosts

- name: 4.2.1.5 - Ensure remote rsyslog messages are only accepted on designated log hosts
  debug:
    msg: "WARNING - This check has not been implemented yet."
  tags:
    - level-1
    - section-4
    - "4.2.1.5"
    - not-scored
    - todo
