---

# 4.2.1.3 Ensure rsyslog default file permissions configured 

- name: 4.2.1.3 - Ensure rsyslog default file permissions configured 
  debug:
    msg: "WARNING - This check has not been implemented yet."
  tags:
    - level-1
    - section-4
    - "4.2.1.3"
    - not-scored
    - todo
