---

# 5.2.16 - Ensure SSH warning banner is configured

- name: 5.2.16 - Ensure SSH warning banner is configured
  lineinfile:
    regexp: "^Banner\\s+"
    line: "Banner {{ cis_sshd_banner }}"
    dest: "/etc/ssh/sshd_config"
  notify:
    - Restart sshd
  tags:
    - level-1
    - section-5
    - "5.2.16"
    - scored
