---

# 5.3.4 Ensure password hashing algorithm is SHA-512

- name: 5.3.4 - Ensure password hashing algorithm is SHA-512
  debug:
    msg: "WARNING - This check has not been implemented yet."
  tags:
    - level-1
    - section-5
    - "5.3.4"
    - scored
    - todo
