---

# 5.3.1 Ensure password creation requirements are configured

- name: 5.3.1 - Ensure password creation requirements are configured
  debug:
    msg: "WARNING - This check has not been implemented yet."
  tags:
    - level-1
    - section-5
    - "5.3.1"
    - scored
    - todo
