---

# 6.2.13 Ensure users' .netrc Files are not group or world accessible

- name: 6.2.13 - Audit users'.netrc permissions
  script: "{{ role_path }}/files/audit_6.2.13.sh"
  register: audit_6_2_13
  tags:
    - level-1
    - section-6
    - "6.2.13"
    - scored

- name: 6.2.13 - Ensure users' .netrc Files are not group or world accessible
  fail:
    msg: "{{ audit_6_2_13.stdout_lines }}"
  when: audit_6_2_13.stdout_lines is defined and audit_6_2_13.stdout_lines|length > 0
  tags:
    - level-1
    - section-6
    - "6.2.13"
    - scored
